require:
  - rubocop-rspec

AllCops:
  StyleGuideBaseURL: https://rubystyle.guide
  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "config/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
  - 'spec/**/*.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/LetSetup:
  Enabled: false

RSpec/ExampleLength:
  Max: 6

Metrics/AbcSize:
  Max: 20

RSpec/RepeatedExampleGroupBody:
  Enabled: false

RSpec/RepeatedExampleGroupDescription:
  Enabled: false
